# Generated by Django 4.1.3 on 2022-11-30 06:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_clip', models.FileField(upload_to='videos/')),
                ('director', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Movies', 'Movies'), ('Webseries', 'Webseries'), ('Kids', 'Kids')], max_length=50)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('content_language', models.CharField(max_length=50)),
                ('summary', models.TextField()),
                ('uploaded', models.DateTimeField(default=datetime.datetime.now)),
                ('free_or_premium', models.CharField(choices=[('free', 'free'), ('premium', 'premium')], max_length=20)),
                ('genre', models.ManyToManyField(related_name='videos', to='home.genre')),
            ],
        ),
    ]
